use piilex_core::finding::{FindingSet, Framework};
use piilex_core::severity::Severity;

pub fn generate_report(finding_set: &FindingSet, framework: Framework) -> String {
    let mut out = String::new();

    let fw_name = framework.as_str().to_uppercase();
    out.push_str(&format!("# {} Compliance Report\n\n", fw_name));
    out.push_str(&format!(
        "Generated: {} | Tool: piilex v{} | Files scanned: {}\n\n",
        chrono_now(),
        finding_set.metadata.tool_version,
        finding_set.metadata.files_scanned,
    ));

    // Executive Summary
    out.push_str("## Executive Summary\n\n");
    let relevant: Vec<_> = finding_set
        .findings
        .iter()
        .filter(|f| {
            f.framework_mappings
                .iter()
                .any(|m| m.framework == framework)
        })
        .collect();

    let critical = relevant
        .iter()
        .filter(|f| f.severity == Severity::Critical)
        .count();
    let high = relevant
        .iter()
        .filter(|f| f.severity == Severity::High)
        .count();
    let medium = relevant
        .iter()
        .filter(|f| f.severity == Severity::Medium)
        .count();
    let low = relevant
        .iter()
        .filter(|f| f.severity == Severity::Low)
        .count();

    out.push_str(&format!(
        "- **Total findings with {} mappings**: {}\n",
        fw_name,
        relevant.len()
    ));
    out.push_str(&format!(
        "- **Critical**: {} | **High**: {} | **Medium**: {} | **Low**: {}\n",
        critical, high, medium, low
    ));

    // Collect unique articles
    let mut articles: Vec<String> = relevant
        .iter()
        .flat_map(|f| {
            f.framework_mappings
                .iter()
                .filter(|m| m.framework == framework)
                .map(|m| m.article.clone())
        })
        .collect();
    articles.sort();
    articles.dedup();
    out.push_str(&format!(
        "- **Articles with findings**: {}\n\n",
        articles.len()
    ));

    // Article-by-article
    out.push_str("## Article-by-Article Assessment\n\n");

    for article in &articles {
        let article_findings: Vec<_> = relevant
            .iter()
            .filter(|f| {
                f.framework_mappings
                    .iter()
                    .any(|m| m.framework == framework && m.article == *article)
            })
            .collect();

        if article_findings.is_empty() {
            continue;
        }

        let mapping = article_findings[0]
            .framework_mappings
            .iter()
            .find(|m| m.framework == framework && m.article == *article)
            .unwrap();

        out.push_str(&format!("### {} — {}\n\n", article, mapping.title));
        out.push_str("| Status | Finding Count | Max Severity |\n");
        out.push_str("|--------|--------------|-------------|\n");

        let max_sev = article_findings
            .iter()
            .map(|f| f.severity)
            .max()
            .unwrap_or(Severity::Low);

        let status = if max_sev >= Severity::High {
            "⚠ AT RISK"
        } else {
            "△ REVIEW"
        };

        out.push_str(&format!(
            "| {} | {} | {} |\n\n",
            status,
            article_findings.len(),
            max_sev
        ));

        out.push_str("**Findings:**\n\n");
        for (i, f) in article_findings.iter().enumerate().take(10) {
            out.push_str(&format!(
                "{}. `{}:{}` — {} ({})\n",
                i + 1,
                f.location.file.display(),
                f.location.line,
                f.pii_type.as_str(),
                f.severity,
            ));
        }
        if article_findings.len() > 10 {
            out.push_str(&format!("... and {} more\n", article_findings.len() - 10));
        }

        out.push_str(&format!(
            "\n**Recommendation:** {}\n\n",
            mapping.recommendation
        ));
        out.push_str("---\n\n");
    }

    // Data flow summary
    out.push_str("## Data Flow Summary\n\n");
    out.push_str("| PII Type | File | Line | Flow |\n");
    out.push_str("|----------|------|------|------|\n");

    for f in relevant.iter().take(20) {
        let flow = f
            .data_flow
            .as_ref()
            .map(|df| format!("{} → {}", df.source.kind.as_str(), df.sink.kind.as_str()))
            .unwrap_or_else(|| "—".to_string());

        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            f.pii_type.as_str(),
            f.location.file.display(),
            f.location.line,
            flow,
        ));
    }

    out.push_str("\n---\n\n");
    out.push_str(&format!(
        "*Report generated by piilex v{}*\n",
        finding_set.metadata.tool_version
    ));

    out
}

fn chrono_now() -> String {
    // Simple date without chrono dependency
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days = now / 86400;
    let years = 1970 + days / 365;
    format!("{}", years)
}
