blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/piilex/piilex/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: Ideas & Discussion
    url: https://github.com/piilex/piilex/discussions/categories/ideas
    about: Share ideas and discuss features
  - name: Discord
    url: https://discord.gg/yTfQme2t
    about: Chat with the community in real-time
